// User Action types
export const SET_USER = "SET_USER";
export const SET_USERS = "SET_USERS";
export const PROCESSING_USER = "PROCESSING_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SET_USER_ERRORS = "SET_USER_ERRORS";
export const CLEAR_USER_ERRORS = "CLEAR_USER_ERRORS";
export const REGISTER_USER = "REGISTER_USER";

// Notification Action Types
export const SET_NOTIFICATION_TOKEN = "SET_NOTIFICATION_TOKEN";
export const PROCESSING_NOTIFICATION = "PROCESSING_NOTIFICATION";
export const PUSH_NOTIFICATION_ERROR = "PUSH_NOTIFICATION_ERROR";

// Job Action types
export const SET_JOBS = "SET_JOBS";
export const PROCESSING_JOB = "PROCESSING_JOB";
export const JOB_ERROR = "JOB_ERROR";
export const SET_USER_JOB = "SET_USER_JOB";
export const SET_JOB_STATUSES = "SET_JOB_STATUSES";
export const PROCESSING_JOB_STATUS = "PROCESSING_JOB_STATUS";
export const JOB_STATUS_ERROR = "JOB_STATUS_ERROR";

// Vessel Action Types
export const SET_VESSELS = "SET_VESSELS";
export const PROCESSING_VESSELS = "PROCESSING_VESSELS";
export const VESSELS_ERROR = "VESSELS_ERROR";

// Logistic Company Action Types
export const SET_LOGISTIC_COMPANIES = "SET_LOGISTIC_COMPANIES";
export const PROCESSING_LOGISTIC_COMPANY = "PROCESSING_LOGISTIC_COMPANY";
export const LOGISTIC_COMPANY_ERROR = "LOGISTIC_COMPANY_ERROR";

// Vessel Loading Location Action Types
export const SET_VESSEL_LOADING_LOCATIONS = "SET_VESSEL_LOADING_LOCATIONS";
export const PROCESSING_VESSEL_LOADING_LOCATIONS =
	"PROCESSING_VESSEL_LOADING_LOCATIONS";
export const VESSEL_LOADING_LOCATIONS_ERROR = "VESSEL_LOADING_LOCATIONS_ERROR";

// Anchorage Locations Action Types
export const SET_ANCHORAGE_LOCATIONS = "SET_ANCHORAGE_LOCATIONS";
export const PROCESSING_ANCHORAGE_LOCATIONS = "PROCESSING_ANCHORAGE_LOCATIONS";
export const ANCHORAGE_LOCATIONS_ERROR = "ANCHORAGE_LOCATIONS_ERROR";
